workflows:
  windows-build:
    name: Windows Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - prod
      node: 16.14.0

    scripts:
      - name: Installing packages
        script: yarn install
      - name: Building Applications
        script: yarn build

    artifacts:
      - out/make/squirrel.windows/x64/*exe
      - out/make/squirrel.windows/x64/*nupkg
      - out/make/zip/win32/x64/*.zip